["int", "0"]
["operator", "..."]
["identifier", "r"]
["right_round", ")"]
["dot_identifier", ".map"]
["left_curly", "{"]
["string", "%\#{(c*r-1).to_s.size+1}d"]
["operator", "%"]
["operator", "~"]
["operator", "-"]
["special_dollar", "$."]
["operator", "+"]
["operator", "="]
["int", "1"]
["right_curly", "}"]
["operator", "*"]
["string", ""]
["right_curly", "}"]

0 ... r ) .map { %#{(c*r-1).to_s.size+1}d % ~ - $. + = 1 } *  }